workflows:
  ios-workflow:
    name: iOS build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "wynford.weather.mission"   # <- change this
        APP_NAME: "Wynford Weather Alerts"                   # <- change this
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - your@email.com   # <- change this
