workflows:
  wynford_weather_alerts_release:
    name: Wynford Weather Alerts Release Build
    environment:
      flutter: stable
      xcode: latest
  # cache removed for validation
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS (release, no code signing)
        script: |
          flutter build ios --release --no-codesign
    artifacts:
  # Android artifact removed; only iOS artifact remains
      - build/ios/iphoneos/Runner.app
  # cache paths moved to environment above
